Repository WooRibound/WooRibound-WEB, pull requests merged in 2024-11, with the labels that each got.

#4 [refactor] #3 - 직무 관련 공통 함수로 리팩토링
  src/App.vue
  src/api/services/globalServiece.js
  src/components/SearchFilterModal.vue
  src/stores/useJobStore.js
  src/views/IndividualUser/JobPostingsPage.vue
  src/views/IndividualUser/WisdomExplore.vue
  src/views/IndividualUser/WisdomShare.vue
  src/views/IndividualUser/WisdomShareRegister.vue
Labels: enhancement

#12 Feature/#2 login
  src/api/services/individualUserService.js
  src/views/Authentication/IndividualUserRegisterView.vue
Labels: enhancement

#22 회원가입 시 직업 명 수정
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/api/services/authenticationService.js
  src/views/Authentication/IndividualUserRegisterView.vue
Labels: enhancement

#24 네이버 로그인 시 회원가입 구현 완료
  src/api/services/individualUserService.js
  src/views/Authentication/IndividualUserRegisterView.vue
Labels: enhancement

#26 기업 회원 가입 시와 정보 수정 시에 사용할 다음 주소 api 설정, 일반 유저 회원가입, 로그인, 기업유저 회원가입, 로그인 완료
  public/index.html
  src/api/services/authenticationService.js
  src/utils/addressFinder.js
  src/views/Authentication/CorporateUserRegisterView.vue
  src/views/Authentication/IndividualUserRegisterView.vue
  src/views/CorporateUser/CorporateUserProfile.vue
Labels: enhancement

#27 Feature/#2 회원탈퇴 처리
  src/api/apiService.js
  src/api/services/authenticationService.js
  src/assets/images/icons/deleted_user.png
  src/router/index.js
  src/router/routes.js
  src/views/Authentication/DeletedUserRedirectView.vue
  src/views/IndividualUser/IndividualUserDelete.vue
Labels: enhancement

#28 Feature/#18 admin individual
  src/views/Admin/IndividualUserManagement.vue
  src/views/CorporateUser/ReadonlyResumePage.vue
Labels: enhancement

#30 탈퇴한 유저의 로그인으로 인한 서버에서 410 반환시 리다이렉트 처리
  src/api/apiService.js
Labels: enhancement

#32 [feat] #10 - 지혜 나눔/등록 관련 API 연동
  src/api/services/individualUserService.js
  src/utils/format.js
  src/views/IndividualUser/WisdomExplore.vue
  src/views/IndividualUser/WisdomExploreDetail.vue
  src/views/IndividualUser/WisdomShare.vue
  src/views/IndividualUser/WisdomShareDelete.vue
  src/views/IndividualUser/WisdomShareRegister.vue
Labels: enhancement

#31 Feature/#18 admin enterprise
  src/components/SearchFilterModal.vue
  src/constants/searchFilterTypes.js
  src/router/routes.js
  src/stores/useIndustriesStore.js
  src/views/Admin/CorporateUserProfileReadonly.vue
  src/views/Admin/CorporateUsersManagement.vue
  src/views/Admin/IndividualUserManagement.vue
  src/views/CorporateUser/ReadonlyResumePage.vue
Labels: enhancement

#33 회원 탈퇴와 회원 탈퇴 확인 화면 및 기능 추가
  src/api/services/authenticationService.js
  src/router/index.js
  src/router/routes.js
  src/views/Common/CorporateDeleteSuccess.vue
  src/views/CorporateUser/CorporateUserDelete.vue
  src/views/IndividualUser/IndividualUserDelete.vue
Labels: enhancement

#35 Feature/#18 admin enterprise
  src/components/TwoButtonModal.vue
  src/views/Admin/CorporateUserSignup.vue
  src/views/Admin/CorporateUserWithdrawal.vue
  src/views/CorporateUser/ReadonlyResumePage.vue
Labels: enhancement

#36 [update] #34 - 알림화면 구현 및 알림 API 연동
  src/api/services/individualUserService.js
  src/assets/images/icons/notification.png
  src/components/HeaderComponent.vue
  src/router/index.js
  src/router/routes.js
  src/stores/useNotificationStore.js
  src/views/Common/FullScreenMenu.vue
  src/views/IndividualUser/NotificationPage.vue
Labels: enhancement

#38 Feature/#18 admin jobposting
  src/views/Admin/CorporateJobPostingManagement.vue
  src/views/Admin/CorporateUsersManagement.vue
  src/views/IndividualUser/JobPostingDetail.vue
  src/views/IndividualUser/WisdomExploreDetail.vue
Labels: enhancement

#39 [fix] 지혜 삭제 취소 시, 모달창만 닫히게 수정
  src/views/IndividualUser/JobPostingDetail.vue
  src/views/IndividualUser/WisdomExploreDetail.vue
Labels: fix

#40 [chore] #18 - 공고 상태 라벨 추가
  src/views/Admin/CorporateJobPostingManagement.vue
  src/views/IndividualUser/JobPostingDetail.vue
Labels: enhancement

#42 [chore] #18 - 서비스 관리자 화면 css 수정
  src/views/Admin/CorporateJobPostingManagement.vue
  src/views/Admin/CorporateUsersManagement.vue
  src/views/IndividualUser/JobPostingDetail.vue
  src/views/IndividualUser/WisdomExploreDetail.vue
Labels: fix

#43 [chore] #18 - 개인회원 목록 css 변경
  src/views/Admin/IndividualUserManagement.vue
Labels: enhancement

#47 [feat] #46 - 기업회원 정보 조회 및 수정
  src/api/services/corporateUserService.js
  src/views/CorporateUser/CorporateUserProfile.vue
Labels: enhancement

#48 [chore] #18 - 서비스 관리자 채용공고 관련 api 분리
  src/api/services/adminServiece.js
  src/api/services/individualUserService.js
  src/views/Admin/CorporateJobPostingManagement.vue
  src/views/IndividualUser/JobPostingDetail.vue
Labels: fix

#50 [feat] #41 - 기업회원 공고등록 API 연동
  src/App.vue
  src/api/services/corporateUserService.js
  src/assets/css/main.css
  src/components/BottomNavigation.vue
  src/components/HeaderComponent.vue
  src/views/Common/MainView.vue
  src/views/CorporateUser/JobPostingRegister.vue
Labels: duplicate

#51 [feat] #2 - 기업회원, 일반유저 탈퇴시 url파라미터를 통해 하나의 .vue파일에서 안내 페이지 처리하도록
  .gitignore
  src/router/index.js
  src/router/routes.js
  src/views/Common/UserDeleteSuccess.vue
  src/views/CorporateUser/CorporateUserDelete.vue
  src/views/IndividualUser/IndividualUserDelete.vue
Labels: enhancement
